on:
  push:
    branches: [ 'main' ]

name: 🚀 Deployment
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Create env file
      run: echo "${{ secrets.DOT_ENV_PRODUCTION }}" > .env

    - name: Create htaccess file
      run: echo "${{ secrets.DOT_HTACCESS }}" > .htaccess
      
    - name: Config Clearing
      run: php artisan config:clear

    - name: Cache Clearing
      run: php artisan cache:clear

    - name: Generate App Key
      run: php artisan key:generate

    - name: Generate storage link
      run: php artisan storage:link

    - name: Generate symlink
      run: ln -s /var/www/vhosts/kepri.pro/beta-sijarimu.kepri.pro/storage/app/public /var/www/vhosts/kepri.pro/beta-sijarimu.kepri.pro/public/storage

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install Npm
      run: npm install

    - name: Compile Css and Js Assets
      run: npm run build

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

#     - name: Create Database
#       run: |
#         mkdir -p database
#         touch database/database.sqlite
#     - name: Create Database
#       run: |
#         mkdir -p database
#         touch database/foodntrack.mysql

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
